com:
  ameripride:
    kafka:
      streams:
        test-consumer-1:
          application-id: test-consumer-1
          source-topic: test-raw-1
          dest-topic: test-compact-1
        test-consumer-2:
          application-id: test-consumer-2
          source-topic: test-compact-1
          dest-topic: test-compact-2

        default:
          state-dir: kafka-streams
          auto-offset-reset: latest
          commit-interval-ms: 10000
          deserialization-error-handler: org.apache.kafka.streams.errors.LogAndContinueExceptionHandler

      producers:
        test-producer-1:
          application-id: test-producer-1
          dest-topic: test-raw-1
        test-producer-2:
          application-id: test-producer-2
          dest-topic: test-raw-1

      bootstrap-servers: localhost:9092
      schema-registry: http://localhost:8081
      application-server: localhost:8072
